// packages/agents/src/lib/storage/driver.ts

export interface PutResult {
  /** Driver-opaque path that can be passed back to get/delete. */
  storage_key: string
  size_bytes: number
  /** Hex-encoded sha256 of the bytes (64 chars). */
  sha256: string
}

export interface PutArgs {
  tenant_id: string
  /** UUID generated by caller. Driver does NOT generate IDs. */
  file_id: string
  bytes: Buffer | NodeJS.ReadableStream
  mime_type: string
}

export interface GetDownloadUrlOpts {
  ttl_seconds?: number
}

export interface FileStorageDriver {
  /**
   * Persist bytes. Returns metadata required to insert into `files` table.
   * Caller is responsible for quota checks BEFORE calling this.
   * Computes sha256 streaming (no double-read).
   */
  put(args: PutArgs): Promise<PutResult>

  /**
   * Read bytes as a stream. Returns null (no throw) if storage_key does not exist.
   */
  get(storage_key: string): Promise<NodeJS.ReadableStream | null>

  /**
   * Idempotent: never throws if storage_key already does not exist.
   */
  delete(storage_key: string): Promise<void>

  /**
   * URL the client uses to download. LocalFs returns a relative URL (e.g.
   * "/api/v1/files/<id>/download") served by the same backend. S3 will return
   * a presigned external URL.
   */
  getDownloadUrl(storage_key: string, opts?: GetDownloadUrlOpts): Promise<string>
}
